Fan Board
lhr-solar/StarterProjects pull request #34
Opened 2024-10-04 20:24 UTC by diyarajon

fan board project.

2024-10-05 00:46 UTC, ppatra126 commented
![image](https://github.com/user-attachments/assets/fb10dd46-7caa-43d7-88d5-bf95276fcbf9)
There are a couple of small things w this schematic. I don't think you need a capacitor and it might add some weird behavior(i am not really sure if it would but it may bc its like an inductor and capacitor in parallel). Typically you put capacitors close to components that require clean power input(microcontrollers or other sensitive ics) because the capacitor can filter out some of the high-frequency noise from propagating to your power input. In this case, it is not super critical that the fans get a super stable power input and therefore it is not really necessary to add a capacitor. Also, you should not need r12. it would constantly be burning power when the fan is on. also please correct me if you had reasoning for adding these components. it is very likely i am being dumb and overlooking things. other than that this subcircuit looks good

2024-10-05 00:51 UTC, ppatra126 commented
![image](https://github.com/user-attachments/assets/c27dcca3-9a54-454c-8c70-2f479b21c84c)
i dont think you need the other resistor in parallel w the diode but i maybe missing something so lmk.

2024-10-23 22:10 UTC, IshDeshpa commented
![image](https://github.com/user-attachments/assets/7b435ec1-dc6a-4907-aaf8-b27ff57df995)
See https://github.com/lhr-solar/StarterProjects/pull/43#issuecomment-2408700293

2024-10-23 22:11 UTC, IshDeshpa commented
Nitpick but you don't need to make stuff this long
![image](https://github.com/user-attachments/assets/943d2573-114e-4a7a-90ea-effbc70af65c)
![image](https://github.com/user-attachments/assets/38cafbbc-cf30-4292-bdb1-b6efeed36697)

2024-10-23 22:12 UTC, IshDeshpa commented
![image](https://github.com/user-attachments/assets/4f366e26-fd9c-404f-84e8-1f20fa14b918)
See https://github.com/lhr-solar/StarterProjects/pull/43#issuecomment-2408701794

2024-10-23 22:13 UTC, IshDeshpa requested changes
Otherwise looks alright.

2025-09-13 02:06 UTC, closed without merging